language: python
sudo: false # build in a container, which is a lot faster! http://docs.travis-ci.com/user/migrating-from-legacy/
cache: pip
python:
    - 3.2
    - 3.3
    - 3.4

install:
    - pip install git+https://github.com/lrq3000/reedsolomon.git
    - pip install codecov
    - pip install 'coverage<4'
    - pip install coveralls

script:
    - coverage run hamming.py test

after_success:
    - coveralls
    - codecov
